### ISSUE TITLE
{"error":{"code":-32601,"message":"Method not found"},"jsonrpc":"2.0"}

### ISSUE THREAD

**Issue by Goldeneum** [FndNur1Labs/DirhamCli#101]
can you plesase help with wallet json rpc ?
./walletd ... (pams)... connected, and recieved coins printed.
but when sending json post as explained here:
https://wiki.bytecoin.org/wiki/Get_status_-_Bytecoin_RPC_Wallet_API

its give and error:

HTTP/1.1 200 OK
Content-Length: 70
Content-Type: application/json
Server: CryptoNote-based HTTP server

{"error":{"code":-32601,"message":"Method not found"},"jsonrpc":"2.0"}

**Comment by FndNur1Labs** [comment]
json still building fixed for security purpose wait for Ruby version out~

**Comment by FndNur1Labs** [comment]
please fork new bcn. they json is fixed. i will try follow up later ;)

**Comment by Goldeneum** [comment]
yes, i already do that and fixe the prob. days ago.
