### ISSUE TITLE
Seed Server

### ISSUE THREAD

**Issue by sverige1** [FndNur1Labs/DirhamCli#84]
I have this setup and i am running my coin..  How do i mine it from and external server?  I can seem to connect to the RPC port.

**Comment by FndNur1Labs** [comment]
make sure 2 side do 1 server seed run ip and used port forwarding. to
target port server from client seed

**Comment by mrtass** [comment]
can u help me setup on my server ? 
i can give u remote access

**Comment by FndNur1Labs** [comment]
wait pm mail ok. crbru.yuthafiga@gmail.com

**Comment by FndNur1Labs** [comment]
if used make easy

**Comment by mrtass** [comment]
Finally it worked, 
i started the seed servers using this command line argument:
--allow-local-ip --seed-node 127.0.0.1:<p2p bind port>
and Node daemons can start without any arguments

thanks alot for your help

**Comment by FndNur1Labs** [comment]
no problem. you can see on doc :)
