### ISSUE TITLE
WARNING [****:*** INC] Exception in connectionHandler: TcpConnection::read

### ISSUE THREAD

**Issue by devnasser** [FndNur1Labs/DirhamCli#99]
hi NUR1LABS
some hours ago im trying to get DirhamCli working without any luck...
im using 2 vps ubuntu in the config seed_nodes[] (already use the same vps's in compiling bytecoin project yesterday and its worked fine).

after compiled the project in the two vps, i run the testnet command on both vps (./dirhamclid --testnet):

########
2018-Feb-04 19:22:17.144489 INFO    dirhamcli v0.0.1.Sapphire-5.2 ()
2018-Feb-04 19:22:17.144818 INFO    Module folder: ./dirhamclid
2018-Feb-04 19:22:17.144934 INFO    Starting in testnet mode!
2018-Feb-04 19:22:17.145214 INFO    Opening DB in /root/.dirhamcli/DB
2018-Feb-04 19:22:17.145960 INFO    DB not found in /root/.dirhamcli/DB. Creating new DB...
2018-Feb-04 19:22:17.173842 INFO    Initializing core...
2018-Feb-04 19:22:17.175801 INFO    Core initialized OK
2018-Feb-04 19:22:17.175923 INFO    Initializing p2p server...
2018-Feb-04 19:22:17.176064 INFO    Generated new peer ID: 9750253326716910705
2018-Feb-04 19:22:17.176175 INFO    Binding on 0.0.0.0:18999
2018-Feb-04 19:22:17.176293 INFO    Net service binded on 0.0.0.0:18999
2018-Feb-04 19:22:17.176377 INFO    Attempting to add IGD port mapping.
2018-Feb-04 19:22:21.181008 INFO    No IGD was found.
2018-Feb-04 19:22:21.181334 INFO    P2p server initialized OK
2018-Feb-04 19:22:21.181569 INFO    Starting core rpc server on address 127.0.0.1:8081
2018-Feb-04 19:22:21.181727 INFO    Core rpc server started ok
2018-Feb-04 19:22:21.181883 INFO    Starting p2p net loop...
2018-Feb-04 19:22:21.181993 INFO    Starting node_server
########

and its stoping here.. !

after that i execute the binary on the first vps: ./dirhamclid
the result was:

########
2018-Feb-04 19:35:10.023327 INFO    dirhamcli v0.0.1.Sapphire-5.2 ()
2018-Feb-04 19:35:10.023668 INFO    Module folder: ./dirhamclid
2018-Feb-04 19:35:10.023951 INFO    Opening DB in /root/.dirhamcli/DB
2018-Feb-04 19:35:10.036373 INFO    DB opened in /root/.dirhamcli/DB
2018-Feb-04 19:35:10.036721 INFO    Initializing core...
2018-Feb-04 19:35:10.040072 INFO    Core initialized OK
2018-Feb-04 19:35:10.040294 INFO    Initializing p2p server...
2018-Feb-04 19:35:10.040508 INFO    Binding on 0.0.0.0:18999
2018-Feb-04 19:35:10.040652 INFO    Net service binded on 0.0.0.0:18999
2018-Feb-04 19:35:10.040830 INFO    Attempting to add IGD port mapping.
2018-Feb-04 19:35:14.047522 INFO    No IGD was found.
2018-Feb-04 19:35:14.047789 INFO    P2p server initialized OK
2018-Feb-04 19:35:14.049631 INFO    Starting core rpc server on address 127.0.0.1:8081
2018-Feb-04 19:35:14.049837 INFO    Core rpc server started ok
2018-Feb-04 19:35:14.049942 INFO    Starting p2p net loop...
2018-Feb-04 19:35:14.050014 INFO    Starting node_server
2018-Feb-04 19:35:14.052868 INFO
2018-Feb-04 19:35:14.052868 INFO    **********************************************************************
2018-Feb-04 19:35:14.052868 INFO    You are now synchronized with the network. You may now start simplewallet.
2018-Feb-04 19:35:14.052868 INFO
2018-Feb-04 19:35:14.052868 INFO    Please note, that the blockchain will be saved only after you quit the daemon with "exit" command or if you use "save" command.
2018-Feb-04 19:35:14.052868 INFO    Otherwise, you will possibly need to synchronize the blockchain again.
2018-Feb-04 19:35:14.052868 INFO
2018-Feb-04 19:35:14.052868 INFO    Use "help" command to see the list of available commands.
2018-Feb-04 19:35:14.052868 INFO    **********************************************************************
2018-Feb-04 19:35:14.054641 WARNING [***my first vps ip***:43964 INC] Exception in connectionHandler: TcpConnection::read
2018-Feb-04 19:35:16.056602 WARNING [***my first vps ip***:39317 INC] Exception in connectionHandler: TcpConnection::read
2018-Feb-04 19:35:18.058714 WARNING [***my first vps ip***:47307 INC] Exception in connectionHandler: TcpConnection::read
..
..
..
########

but when lunching the second binary (in the second vps): ./dirhamclid

the first  vps show me this repeatitive messages:

########
2018-Feb-04 19:38:00.739452 WARNING [**my first vps ip**:52962 INC] Exception in connectionHandler: TcpConnection::read
2018-Feb-04 19:38:02.742172 ERROR   [**my second vps ip**:18999 OUT] Failed to invoke COMMAND_HANDSHAKE, closing connection.
2018-Feb-04 19:38:02.742279 WARNING Failed to HANDSHAKE with peer **my second vps ip**:18999
2018-Feb-04 19:38:02.743730 WARNING [**my first vps ip**:44784 INC] Exception in connectionHandler: TcpConnection::read
########

the plus point here is the message:
########
[**my second vps ip**:18999 OUT] Failed to invoke COMMAND_HANDSHAKE, closing connection
########
and in the second vps screen i get this repeatitive message:

########
2018-Feb-04 19:37:34.674524 INFO    dirhamcli v0.0.1.Sapphire-5.2 ()
2018-Feb-04 19:37:34.675009 INFO    Module folder: ./dirhamclid
2018-Feb-04 19:37:34.675229 INFO    Starting in testnet mode!
2018-Feb-04 19:37:34.675700 INFO    Opening DB in /root/.dirhamcli/DB
2018-Feb-04 19:37:34.694039 INFO    DB opened in /root/.dirhamcli/DB
2018-Feb-04 19:37:34.694489 INFO    Initializing core...
2018-Feb-04 19:37:34.698988 INFO    Core initialized OK
2018-Feb-04 19:37:34.699214 INFO    Initializing p2p server...
2018-Feb-04 19:37:34.699425 INFO    Binding on 0.0.0.0:18999
2018-Feb-04 19:37:34.699619 INFO    Net service binded on 0.0.0.0:18999
2018-Feb-04 19:37:34.699749 INFO    Attempting to add IGD port mapping.
2018-Feb-04 19:37:38.704567 INFO    No IGD was found.
2018-Feb-04 19:37:38.704893 INFO    P2p server initialized OK
2018-Feb-04 19:37:38.705291 INFO    Starting core rpc server on address 127.0.0.1:8081
2018-Feb-04 19:37:38.705514 INFO    Core rpc server started ok
2018-Feb-04 19:37:38.705691 INFO    Starting p2p net loop...
2018-Feb-04 19:37:38.705831 INFO    Starting node_server
2018-Feb-04 19:37:38.707391 INFO    [**my first vps ip**:47781 INC] WRONG NETWORK AGENT CONNECTED! id=09100111-1100-0101-1011-001210110110
2018-Feb-04 19:37:54.724912 INFO    [**my first vps ip**:59582 INC] WRONG NETWORK AGENT CONNECTED! id=09100111-1100-0101-1011-001210110110
2018-Feb-04 19:37:56.729356 INFO    [**my first vps ip**:55976 INC] WRONG NETWORK AGENT CONNECTED! id=09100111-1100-0101-1011-001210110110
2018-Feb-04 19:37:58.733302 INFO    [**my first vps ip**:54152 INC] WRONG NETWORK AGENT CONNECTED! id=09100111-1100-0101-1011-001210110110
2018-Feb-04 19:38:02.739227 INFO    [**my first vps ip**:49037 INC] WRONG NETWORK AGENT CONNECTED! id=09100111-1100-0101-1011-001210110110
########

the problem is when i recompile bytecoin code (i do that to test it again) its show me this error on both vps :
`WARNING [****:*** INC] Exception in connectionHandler: TcpConnection::read` !!!

do you have any idea about this errors?
what you perpose for?

sorry for the long issue text, and for bad english :D

Thank you in advance :)

**Comment by devnasser** [comment]
#update
bytecoin wirking now (i just changed the name of coin in config and cmakeliste then recompile the whole code.

but still unable to get your code working !!! its a forked of bytecoin, why i get the errors below?

another thing, its about premined.
how to do that?
after executing ./miner --address (the first created address) give me 2111046.21924351 unlocked balance in the wallet.
lunch the miner in the second vps doesnt slove the problem, the balance still "unlocked".
the balance now is up 3500000 coin, after some minutes of mining !!! its a height reward !
how to reduce the reward and get specified % premined ?

last question here (im realy sorry , i'm still studying this technology ^^!):
how set up external pool for this project (as democats.org or minexmr.com... etc)? can i set up the pool on one of vps used in see_nodes[] ?

thank you :)

**Comment by devnasser** [comment]
#update:
2018-Feb-04 22:45:24.405321 INFO    available balance: 2111046.21924351, locked amount: 6332993.70534903

its apear that the mining is okay, wallet, deamon and everythink.
now im trying to setup js miner on vps nginx srver, i want to simulate coinhive :D
still cant mining remotly -from my pc-... the miner tell me: connection reset by peer. and the dytecoind show me the message :
`WARNING [my pnetwork ip:port INC] Exception in connectionHandler: TcpConnection::read`
claymore miner also telling me that the wallet address i invald (i use prefex in cryptonote configuration file).. so use xmrig to test remote mining (i mean mining out of the 2 vps).
should i use diffirent vps and execute bytecoind on it to the mining?

please, answer my questions in this issue ticket.
thank you :)

**Comment by FndNur1Labs** [comment]
first one used local ip and second one is for target to public ip seed.
open port needed and check by netstat will it listened. and about handshake
i will try it now. if mine same bug or not~

**Comment by FndNur1Labs** [comment]
./daemon --allow-local-ip --seed-node 127.0.0.1
